### PR TITLE
delete unused import 

### PR DESCRIPTION
**Pull request by kouhei**
`import { Document } from '@contentful/rich-text-types';` is not need when we don't use richText.
But it contained always.
This may cause failing linter.
So I modified to contain `import { Document } from '@contentful/rich-text-types';` when only use it.

I think #106 solved by this PR.

I would be grateful if you review this PR.

### CODE REVIEW

**Comment by kouhei** [comment]
Repo is not maintained?

**Comment by GabrielAnca** [comment]
Hi @kouhei 👋🏻 Your PR looks great. There's a conflict now. Do you mind rebasing and renaming your commit to adhere to the [semantic release format](https://github.com/semantic-release/semantic-release/blob/master/README.md#commit-message-format)? Something like `fix(renderContentfulImport): Only import Document when needed` would work!

Once that's done I'll get it merged. Thank you!

**Review by GabrielAnca — APPROVED** [review]
Looks great, thanks a lot for this contribution @kouhei 🎉

**Pull request merged**
